//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TO_Project.Util.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mensagens {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensagens() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TO_Project.Util.Resources.Mensagens", typeof(Mensagens).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor mínimo a ser liberado é de R$ 15.000,00..
        /// </summary>
        public static string Erro_CreditoPJ {
            get {
                return ResourceManager.GetString("Erro_CreditoPJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data do primeiro vencimento deve estar entre {0} e {1}..
        /// </summary>
        public static string Erro_DataPrimeiroVencimento {
            get {
                return ResourceManager.GetString("Erro_DataPrimeiroVencimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de primeiro vencimento inválida..
        /// </summary>
        public static string Erro_DataPrimeiroVencimentoInvalida {
            get {
                return ResourceManager.GetString("Erro_DataPrimeiroVencimentoInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parâmetro não mapeado..
        /// </summary>
        public static string Erro_ParametroNaoMapeado {
            get {
                return ResourceManager.GetString("Erro_ParametroNaoMapeado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A quantidade de parcelas deve estar entre 5 e 72x..
        /// </summary>
        public static string Erro_QuantidadeParcelas {
            get {
                return ResourceManager.GetString("Erro_QuantidadeParcelas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantidade de parcelas inválida..
        /// </summary>
        public static string Erro_QuantidadeParcelasInvalida {
            get {
                return ResourceManager.GetString("Erro_QuantidadeParcelasInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de crédito inválido..
        /// </summary>
        public static string Erro_TipoCreditoInvalido {
            get {
                return ResourceManager.GetString("Erro_TipoCreditoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor do crédito não pode ser negativo..
        /// </summary>
        public static string Erro_ValorCreditoInvalido {
            get {
                return ResourceManager.GetString("Erro_ValorCreditoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor de crédito inválido..
        /// </summary>
        public static string Erro_ValorCreditoInvalido2 {
            get {
                return ResourceManager.GetString("Erro_ValorCreditoInvalido2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor do crédito máximo a ser liberado é de R$ 1.000.000,00..
        /// </summary>
        public static string Erro_ValorMaximoUltrapassado {
            get {
                return ResourceManager.GetString("Erro_ValorMaximoUltrapassado", resourceCulture);
            }
        }
    }
}
